### ISSUE TITLE
Issue with loading shared library in docker image

### ISSUE THREAD

**Issue by patrick-njit** [PDAL/java#59]
I am trying to build a pipeline in scala in an alpine docker image. I have copied my DockerFile below

```
FROM alpine:latest

RUN apk add openjdk17 curl bash pdal-dev && \
    curl -fLo coursier https://github.com/coursier/launchers/raw/master/coursier && \
    chmod +x coursier && \
    /coursier install scala:2.12.10 && \
    /coursier install scalac:2.12.10 && \
    /coursier install sbt
```

I have created my project using the scala/hello-world.g8 template. I have modified my build.sbt and main.scala as follows

build.sbt
```
scalaVersion := "2.13.8"

val pdalVersion = "2.3.1"

libraryDependencies ++= Seq(
  "io.pdal" %% "pdal"        % pdalVersion,
  "io.pdal" %% "pdal-scala"  % pdalVersion,
  "io.pdal" %  "pdal-native" % pdalVersion,
)
```

scr/main/scala/Main.scala
```
import io.pdal._
import io.pdal.pipeline._

import scala.collection.JavaConverters._
import scala.language.implicitConversions


object Main extends App {

  var javaLibraryPath = System.getProperties().asScala.get("java.library.path").get;
  println(javaLibraryPath);

  val expression =
    ReadLas("1.2-with-color.las", spatialreference = Some("EPSG:2993")) ~
    FilterReprojection("EPSG:3857") ~
    FilterDelaunay()

  val pipeline = expression.toPipeline
  pipeline.validate()
}
```

Running the project from sbt returns the error

```
# sbt run
[info] welcome to sbt 1.6.2 (Alpine Java 17.0.3)
[info] loading project definition from /workspaces/testing/hello-world/project
[info] loading settings for project hello-world from build.sbt ...
[info] set current project to hello-world (in build file:/workspaces/testing/hello-world/)
[info] running Main 
/usr/lib/jvm/java-17-openjdk/lib/server:/usr/lib/jvm/java-17-openjdk/lib:/usr/lib/jvm/java-17-openjdk/../lib:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Exception in thread "sbt-bg-threads-1" java.lang.UnsatisfiedLinkError: /tmp/jni-13819220931716823972/libpdaljni.2.3.so: Error loading shared library libpdal_base.so.13: No such file or directory (needed by /tmp/jni-13819220931716823972/libpdaljni.2.3.so)
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
        at java.base/java.lang.Runtime.load0(Runtime.java:755)
        at java.base/java.lang.System.load(System.java:1953)
        at com.github.sbt.jni.syntax.NativeLoader$.loadPackaged$1(NativeLoader.scala:50)
        at com.github.sbt.jni.syntax.NativeLoader$.load$1(NativeLoader.scala:56)
        at com.github.sbt.jni.syntax.NativeLoader$.load(NativeLoader.scala:59)
        at com.github.sbt.jni.syntax.NativeLoader.<init>(NativeLoader.scala:6)
        at io.pdal.Pipeline$.<init>(Pipeline.scala:44)
        at io.pdal.Pipeline$.<clinit>(Pipeline.scala:44)
        at io.pdal.pipeline.PipelineConstructor.toPipeline(PipelineConstructor.scala:32)
        at Main$.delayedEndpoint$Main$1(Main.scala:18)
        at Main$delayedInit$body.apply(Main.scala:8)
        at scala.Function0.apply$mcV$sp(Function0.scala:39)
        at scala.Function0.apply$mcV$sp$(Function0.scala:39)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
        at scala.App.$anonfun$main$1(App.scala:76)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at Main$.main(Main.scala:8)
        at Main.main(Main.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at sbt.Run.invokeMain(Run.scala:143)
        at sbt.Run.execute$1(Run.scala:93)
        at sbt.Run.$anonfun$runWithLoader$5(Run.scala:120)
        at sbt.Run$.executeSuccess(Run.scala:186)
        at sbt.Run.runWithLoader(Run.scala:120)
        at sbt.Defaults$.$anonfun$bgRunTask$6(Defaults.scala:1983)
        at sbt.Defaults$.$anonfun$termWrapper$2(Defaults.scala:1922)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.util.Try$.apply(Try.scala:213)
        at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:369)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
[success] Total time: 1 s
```

Pdal is installed in `/usr/lib`, which is on javaLibraryPath. The pdal bindings should be located in `/usr/lib`.

```
# find / -name libpdal*
/usr/lib/libpdal_plugin_kernel_fauxplugin.so
/usr/lib/libpdal_plugin_reader_pgpointcloud.so.14.0.0
/usr/lib/libpdal_plugin_writer_pgpointcloud.so.14
/usr/lib/libpdalcpp.so
/usr/lib/libpdal_plugin_kernel_fauxplugin.so.14
/usr/lib/libpdal_util.so.14.0.0
/usr/lib/libpdal_util.so
/usr/lib/libpdal_plugin_reader_icebridge.so.14.0.0
/usr/lib/libpdal_plugin_filter_cpd.so.14
/usr/lib/libpdal_base.so
/usr/lib/libpdal_base.so.14.0.0
/usr/lib/libpdal_plugin_kernel_fauxplugin.so.14.0.0
/usr/lib/libpdal_plugin_reader_pgpointcloud.so.14
/usr/lib/libpdal_plugin_filter_cpd.so
/usr/lib/libpdal_plugin_reader_pgpointcloud.so
/usr/lib/libpdal_base.so.14
/usr/lib/libpdal_plugin_reader_icebridge.so.14
/usr/lib/libpdal_util.so.14
/usr/lib/libpdal_plugin_filter_cpd.so.14.0.0
/usr/lib/libpdal_plugin_reader_icebridge.so
/usr/lib/libpdal_plugin_writer_pgpointcloud.so.14.0.0
/usr/lib/libpdal_plugin_writer_pgpointcloud.so
/tmp/jni-8189681954144514568/libpdaljni.2.3.so
/tmp/jni-13819220931716823972/libpdaljni.2.3.so
/tmp/jni-2250992258675823159/libpdaljni.2.3.so
/tmp/jni-4101027605469123869/libpdaljni.2.3.so
```

So I have `libpdal_base.so.14.0.0` wheras the jni is looking for `libpdal_base.so.13`. Do I need to get the correct version or is there another issue entirely?

**Comment by pomadchin** [comment]
Hey @patrick-njit I think indeed a slightly mismastched version. You may try with PDAL 2.3.0, `daunnc/pdal-ubuntu:2.3.0`, or symlink `libpdal_base.so.14.0.0` to `libpdal_base.so.13` and it might work. 

Otherwise, I'd need to cut a fresh release.

A super alternative option is to build bindings from source, you can find instructions in the [README.md](https://github.com/PDAL/java#how-to-compile)

**Comment by patrick-njit** [comment]
Creating symbolic links seems to work for the moment. Hopefully I don't run into issues later. Thank you very much for your help!

**Comment by pomadchin** [comment]
@patrick-njit i created a follow up issue to upgrade PDAL version https://github.com/PDAL/java/issues/60

**Comment by pomadchin** [comment]
Closed via https://github.com/PDAL/java/issues/60
